FROM node:18-alpine

WORKDIR /app

# Build-time env
ARG NEXT_PUBLIC_FANTASY_DASHBOARD_URL
ARG NEXT_PUBLIC_FANTASY_COMPETITION_ID
ARG NEXT_PUBLIC_FANTASY_API_BASE_URL
ARG FANTASY_API_BASE_URL

ENV NEXT_PUBLIC_FANTASY_DASHBOARD_URL=$NEXT_PUBLIC_FANTASY_DASHBOARD_URL
ENV NEXT_PUBLIC_FANTASY_API_BASE_URL=$NEXT_PUBLIC_FANTASY_API_BASE_URL
ENV NEXT_PUBLIC_FANTASY_COMPETITION_ID=$NEXT_PUBLIC_FANTASY_COMPETITION_ID
ENV FANTASY_API_BASE_URL=$FANTASY_API_BASE_URL

COPY package*.json ./
COPY yarn.lock* ./

RUN npm ci || yarn install || npm install

COPY . .

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
